Register in Send To menu instead of plugins toolbar
AllegorithmicSAS/painter-plugin-photoshop-export pull request #46
Opened 2021-04-07 15:12 UTC by mosseb

2021-04-09 09:29 UTC, mosseb commented
Need to update Ps icons

2021-04-09 13:24 UTC, mosseb commented
Welln turns out the icons were already up to date.

2021-04-15 12:34 UTC, PhilippeHermite commented on main.qml
> +	property bool loading: false
Since you have an internal object, you should move this property inside it

2021-04-15 12:39 UTC, PhilippeHermite requested changes
You should update the plugin version and the min api in the plugin config
Aren't the translation missing?

2021-04-15 14:28 UTC, closed without merging